name: C/C++ CI
on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    name: build

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: ./configure
    - name: make
      run: curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next/kernel/setup.sh" | bash -
           make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
